### ISSUE TITLE
Contributing to the documentation

### ISSUE THREAD

**Issue by jonovs** [Unleash/unleash.github.io#1]
I've spotted a few typos I could help fix. However, it seems that this website is automatically generated, and I can't seem to find any sources or instructions for updating the website.

@ivarconr If contributions are welcome, I'd love to get a brief how-to on this (e.g. README).

**Comment by ivarconr** [comment]
Aha, yes this repo is totally generated from the main Unleash repo. I shall look in to also copying the README.md over here to not confuse more people. 

The Unleash website is created with Docusaurus. You should find the readme here:
https://github.com/Unleash/unleash/tree/master/website

All help is highly appreciated.

**Comment by jonovs** [comment]
Ah, there it is! Thanks 👍
