### ISSUE TITLE
"Securing unleash"-link gives 404

### ISSUE THREAD

**Issue by madsop** [Unleash/unleash.github.io#4]
https://unleash.github.io/docs/en/securing_unleash.html gives me a 404 page not found.

(Link in the footer on https://unleash.github.io/docs/developer_guide )

**Comment by ivarconr** [comment]
woops. thanks there is no localisation in place so we need to drop "en". I will look in to it!

**Comment by ivarconr** [comment]
Fixed in https://github.com/Unleash/unleash/commit/b637a600f2cb5346d5113c720eddfe2479df7539 and will be updated after build + cache invalidatation
